"""add phone number to users table

Revision ID: 060de3737fa0
Revises: 903201418c62
Create Date: 2022-06-15 12:35:39.485451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060de3737fa0'
down_revision = '903201418c62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###



############## alembic revision --autogenerate -m "add phone number to users table"